const lessons=[
 {title:"Recognising facial emotions",body:`<p class="lead">We can use the eyes, eyebrows and mouth as clues. Look at the whole face before choosing.</p><div class="lesson-panel"><h2>Three useful clues</h2><div class="emotion-cues"><div class="cue"><b>🙂</b><strong>Happy</strong><br><small>Smile, relaxed eyes</small></div><div class="cue"><b>☹</b><strong>Sad</strong><br><small>Downturned mouth, lowered gaze</small></div><div class="cue"><b>😮</b><strong>Surprised</strong><br><small>Raised eyebrows, wide eyes</small></div></div></div>`},
 {title:"Everyday maths",body:`<p class="lead">Read the question, notice the operation, and work one step at a time.</p><div class="lesson-panel"><h2>Example: addition</h2><div class="equation">12 + 7 = 19</div><p>Start at 12 and count forward 7. For percentages, 50% means half.</p></div>`},
 {title:"Clear English",body:`<p class="lead">A sentence shares a complete idea. Context clues help us understand unfamiliar words.</p><div class="lesson-panel"><h2>Example</h2><div class="example-sentence">“Mira carried an umbrella because the sky was dark.”</div><p>The word <strong>because</strong> gives a reason. A synonym is a word with the same or a similar meaning.</p></div>`}
];
const questions=[
 {subject:"Faces",text:"What emotion is this person showing?",image:"happy.png",options:["Happy","Angry","Confused"],answer:"Happy"},
 {subject:"Maths",text:"What is 12 + 7?",options:["17","19","21"],answer:"19"},
 {subject:"English",text:"Choose the word that means the same as ‘quick’.",options:["Slow","Fast","Quiet"],answer:"Fast"},
 {subject:"Faces",text:"What emotion is this person showing?",image:"sad.png",options:["Excited","Sad","Surprised"],answer:"Sad"},
 {subject:"Maths",text:"What is 20 − 8?",options:["10","12","14"],answer:"12"},
 {subject:"English",text:"Which sentence is complete?",options:["Under the table.","The dog slept under the table.","Because the dog."],answer:"The dog slept under the table."},
 {subject:"Faces",text:"What emotion is this person showing?",image:"surprised.png",options:["Surprised","Bored","Sad"],answer:"Surprised"},
 {subject:"Maths",text:"What is half of 18?",options:["6","8","9"],answer:"9"},
 {subject:"English",text:"Which word best completes the sentence: ‘The sun is very ___.’",options:["bright","quietly","jump"],answer:"bright"},
 {subject:"Maths",text:"A notebook costs ₹40. How much do two notebooks cost?",options:["₹60","₹80","₹90"],answer:"₹80"}
];
const $=id=>document.getElementById(id);let state={condition:"adapted",participantId:"",lesson:0,question:0,answers:[],startedAt:0,phaseStartedAt:0,changes:0,sessionId:""};
document.querySelectorAll('input[name="condition"]').forEach(r=>r.addEventListener("change",e=>{document.querySelectorAll(".condition-card").forEach(x=>x.classList.remove("selected"));e.target.closest(".condition-card").classList.add("selected");document.querySelectorAll(".choice-check").forEach(x=>x.textContent="Select");e.target.closest(".condition-card").querySelector(".choice-check").textContent="Selected";}));
$("setupForm").addEventListener("submit",e=>{e.preventDefault();state.condition=document.querySelector('input[name="condition"]:checked').value;state.participantId=$("participantId").value.trim();state.startedAt=performance.now();state.phaseStartedAt=performance.now();state.sessionId=`${Date.now()}-${Math.random().toString(36).slice(2,8)}`;$("app").className=`app ${state.condition}`;$("conditionBadge").textContent=state.condition==="adapted"?"Autism-adapted interface":"Standard interface";show("lessonView");$("progressShell").classList.remove("hidden");renderLesson();recordEvent("session_started",{condition:state.condition});});
$("nextLesson").addEventListener("click",()=>{recordEvent("lesson_completed",{lesson:state.lesson+1,duration_ms:Math.round(performance.now()-state.phaseStartedAt)});state.lesson++;state.phaseStartedAt=performance.now();if(state.lesson<lessons.length)renderLesson();else{state.question=0;show("quizView");renderQuestion();}});
function renderLesson(){const l=lessons[state.lesson];$("lessonKicker").textContent=`Lesson ${state.lesson+1} of 3`;$("lessonTitle").textContent=l.title;$("lessonBody").innerHTML=l.body;$("nextLesson").innerHTML=state.lesson===2?'Start the test <span aria-hidden="true">→</span>':'Next lesson <span aria-hidden="true">→</span>';setProgress((state.lesson+1)/4,`Lesson ${state.lesson+1} of 3`);focusMain();}
function renderQuestion(){const q=questions[state.question];state.phaseStartedAt=performance.now();state.changes=0;$("subjectPill").textContent=q.subject;$("questionCount").textContent=`Question ${state.question+1} of 10`;$("questionText").textContent=q.text;$("questionVisual").innerHTML=q.image?`<img class="face-stimulus" src="${q.image}" alt="A person showing an emotion" />`:"";$("answers").innerHTML=q.options.map((o,i)=>`<label class="answer-option"><input type="radio" name="answer" value="${escapeHtml(o)}"><span>${String.fromCharCode(65+i)}. ${escapeHtml(o)}</span></label>`).join("");$("answerMessage").classList.add("hidden");$("nextQuestion").disabled=true;$("nextQuestion").innerHTML=state.question===9?'See results <span aria-hidden="true">→</span>':'Continue <span aria-hidden="true">→</span>';$("answers").addEventListener("change",chooseAnswer);renderDots();setProgress((3+((state.question+1)/10))/4,`Test · Question ${state.question+1} of 10`);focusMain();}
function chooseAnswer(e){state.changes++;document.querySelectorAll(".answer-option").forEach(x=>x.classList.remove("selected"));e.target.closest(".answer-option").classList.add("selected");$("nextQuestion").disabled=false;const q=questions[state.question],correct=e.target.value===q.answer;$("answerMessage").textContent=correct?"Answer recorded. You can continue.":"Answer recorded. You can still continue.";$("answerMessage").classList.remove("hidden");}
$("nextQuestion").addEventListener("click",()=>{const selected=document.querySelector('input[name="answer"]:checked');if(!selected)return;const q=questions[state.question];state.answers.push({question:state.question+1,subject:q.subject,response:selected.value,correct:selected.value===q.answer,response_ms:Math.round(performance.now()-state.phaseStartedAt),answer_changes:Math.max(0,state.changes-1)});recordEvent("answer_submitted",state.answers.at(-1));state.question++;if(state.question<questions.length)renderQuestion();else finish();});
async function finish(){const ended=performance.now(),score=state.answers.filter(a=>a.correct).length;const session={session_id:state.sessionId,participant_id:state.participantId,condition:state.condition,started_at:new Date(Date.now()-(ended-state.startedAt)).toISOString(),completed_at:new Date().toISOString(),completed:true,total_duration_ms:Math.round(ended-state.startedAt),score,incorrect:10-score,answers:state.answers,user_agent:navigator.userAgent,viewport:`${innerWidth}x${innerHeight}`};await saveSession(session);show("resultsView");$("progressShell").classList.add("hidden");$("scoreValue").textContent=$("correctValue").textContent=score;$("incorrectValue").textContent=10-score;$("scoreBar").style.width=`${score*10}%`;$("saveStatus").textContent="Saved locally at "+new Date().toLocaleTimeString();focusMain();}
function setProgress(v,label){$("progressBar").style.width=`${Math.round(v*100)}%`;$("percentLabel").textContent=`${Math.round(v*100)}%`;$("stepLabel").textContent=label}function renderDots(){$("questionDots").className="question-dots";$("questionDots").innerHTML=questions.map((_,i)=>`<span class="dot ${i<state.question?'done':i===state.question?'current':''}">${i<state.question?'✓':i+1}</span>`).join("")}function show(id){["setupView","lessonView","quizView","resultsView"].forEach(x=>$(x).classList.toggle("hidden",x!==id))}function focusMain(){scrollTo({top:0,behavior:state.condition==="adapted"?"auto":"smooth"});$("main").focus()}function escapeHtml(s){return s.replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function db(){return new Promise((resolve,reject)=>{const r=indexedDB.open("codexLearnStudy",1);r.onupgradeneeded=()=>r.result.createObjectStore("sessions",{keyPath:"session_id"});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}async function saveSession(s){const d=await db();return new Promise((resolve,reject)=>{const t=d.transaction("sessions","readwrite");t.objectStore("sessions").put(s);t.oncomplete=resolve;t.onerror=()=>reject(t.error)})}async function allSessions(){const d=await db();return new Promise((resolve,reject)=>{const r=d.transaction("sessions").objectStore("sessions").getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}function recordEvent(type,data){const log=JSON.parse(sessionStorage.getItem("codexEvents")||"[]");log.push({session_id:state.sessionId,type,at:new Date().toISOString(),...data});sessionStorage.setItem("codexEvents",JSON.stringify(log))}
$("downloadCsv").addEventListener("click",async()=>{const sessions=await allSessions(),rows=[["session_id","participant_id","condition","started_at","completed_at","completed","total_duration_ms","score","incorrect","question","subject","response","correct","response_ms","answer_changes","viewport"]];sessions.forEach(s=>s.answers.forEach(a=>rows.push([s.session_id,s.participant_id,s.condition,s.started_at,s.completed_at,s.completed,s.total_duration_ms,s.score,s.incorrect,a.question,a.subject,a.response,a.correct,a.response_ms,a.answer_changes,s.viewport])));const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\r\n"),url=URL.createObjectURL(new Blob([csv],{type:"text/csv"})),a=document.createElement("a");a.href=url;a.download=`codex-study-data-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url)});$("newParticipant").addEventListener("click",()=>location.reload());$("soundToggle").addEventListener("click",e=>{const on=e.currentTarget.getAttribute("aria-pressed")==="true";e.currentTarget.setAttribute("aria-pressed",String(!on));e.currentTarget.textContent=on?"Sound off":"Sound on"});
addEventListener("beforeunload",()=>{if(state.sessionId&&state.answers.length<10)recordEvent("session_abandoned",{last_question:state.question+1,answers_completed:state.answers.length})});
