const app=document.querySelector('#app');
const C=['adapted','conventional'],L={adapted:'Autism-adapted interface',conventional:'Standard interface'};
const s={page:'home',person:null,mode:null,condition:null,index:0,step:0,answer:null,feedback:null,started:0,events:[],results:[],help:0};
const work=[
['lesson','Emotions','Recognising feelings','A smile can mean happy. A downturned mouth can mean sad. Wide eyes and an open mouth can mean surprised. Look at the whole face.','😊'],
['lesson','Maths','Easy number skills','Addition puts numbers together. Subtraction takes away. Half means two equal parts. Example: 4 + 3 = 7 and half of 10 = 5.','4 + 3 = 7'],
['lesson','English','Easy English skills','A noun names a person, place, animal, or thing. A verb is an action word. The main idea tells what a sentence is mostly about.','The dog runs.'],
['test','Emotions','What feeling is shown?','Choose the feeling shown by this face.','😊',['Happy','Sad','Angry','Surprised'],'Happy'],
['test','Emotions','What feeling is shown?','Choose the feeling shown by this face.','😢',['Calm','Happy','Sad','Surprised'],'Sad'],
['test','Emotions','What feeling is shown?','Choose the feeling shown by this face.','😮',['Sad','Surprised','Calm','Happy'],'Surprised'],
['test','Emotions','What feeling is shown?','Choose the feeling shown by this face.','😌',['Calm','Surprised','Sad','Angry'],'Calm'],
['test','Maths','Add the numbers','What is 2 + 5?','2 + 5',['5','6','7','8'],'7'],
['test','Maths','Subtract the numbers','What is 10 − 4?','10 − 4',['4','5','6','7'],'6'],
['test','Maths','Find one half','What is half of 12?','½ of 12',['4','5','6','8'],'6'],
['test','English','Choose the noun','Which word names an animal?','Aa',['Quickly','Jump','Rabbit','Blue'],'Rabbit'],
['test','English','Choose the verb','Which word is an action?','Aa',['Table','Run','Yellow','School'],'Run'],
['test','English','Choose the main idea','Sam feeds his cat every morning. What is this sentence mostly about?','Aa',['Sam cares for his cat','Morning is cold','Cats can fly','Sam goes to school'],'Sam cares for his cat']];
const safe=x=>String(x).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
function save(){if(s.person)localStorage.setItem('codex-study-'+s.person.id,JSON.stringify({participant:s.person,results:s.results,events:s.events}))}
function log(type,data={}){s.events.push({type,condition:s.condition,step:s.step,time:new Date().toISOString(),elapsedMs:s.started?Date.now()-s.started:0,...data});save()}
function order(id){return [...id].reduce((n,c)=>n+c.charCodeAt(0),0)%2?C:[...C].reverse()}
function go(page){s.page=page;draw();scrollTo(0,0)}
function draw(){document.body.className=s.condition==='conventional'?'conventional':'';({home,setup,learn,survey,pause,done}[s.page]||home)()}
function home(){app.innerHTML=`<main class="shell"><header class="topbar"><div class="brand"><span class="brand-mark">CL</span>Codex Learning Study</div><span class="pill">Research prototype</span></header><section class="hero"><div><p class="eyebrow">Educational interface study</p><h1>Learn first.<br>Then answer 10 easy questions.</h1><p class="lead">Three simple lessons cover emotions, maths, and English. Choose either interface or compare both.</p><button class="btn" onclick="go('setup')">Choose an interface</button></div><aside class="hero-card"><p class="big-number">3 + 10</p><h2>Lessons + test</h2><p class="muted">Easy language and basic skills throughout.</p></aside></section><div class="subject-grid">${[['☺','Emotions'],['+','Maths'],['Aa','English']].map(x=>`<article class="card"><div class="formula">${x[0]}</div><h2>${x[1]}</h2><p class="muted">Learn, then practise.</p></article>`).join('')}</div></main>`}
function setup(){let options=[['adapted','Autism-adapted interface','Calm, clear, predictable, and adjustable.'],['conventional','Standard interface','Same tasks with a busier presentation.'],['both','Compare both interfaces','Complete both with a break between them.']];app.innerHTML=`<main class="shell"><header class="topbar"><div class="brand">Codex Learning Study</div><button class="btn secondary" onclick="go('home')">Back</button></header><section class="stage"><p class="eyebrow">Session setup</p><h1>Choose an interface</h1><form class="card" onsubmit="start(event)"><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:14px">${options.map(x=>`<label class="card" style="padding:18px;cursor:pointer"><input type="radio" name="mode" value="${x[0]}" required> <strong>${x[1]}</strong><p class="muted">${x[2]}</p></label>`).join('')}</div><div class="form-grid" style="margin-top:22px"><div class="field"><label>Participant ID</label><input id="pid" required pattern="[A-Za-z0-9_-]+" placeholder="P014"></div><div class="field"><label>Age</label><input id="age" type="number" min="10" max="18" required></div><div class="field"><label>Input method</label><select id="input"><option>Mouse</option><option>Touchscreen</option><option>Keyboard</option></select></div><div class="field"><label>Support</label><select id="support"><option>Independent</option><option>Verbal prompts</option><option>Navigation support</option></select></div></div><hr><label class="check"><input type="checkbox" required> Consent and assent are confirmed.</label><label class="check"><input type="checkbox" required> The participant may pause or stop at any time.</label><button class="btn" style="margin-top:20px">Start lessons</button></form></section></main>`}
function start(e){e.preventDefault();let id=document.querySelector('#pid').value,mode=new FormData(e.target).get('mode'),o=mode==='both'?order(id):[mode];s.mode=mode;s.person={id,age:+document.querySelector('#age').value,input:document.querySelector('#input').value,support:document.querySelector('#support').value,order:o,createdAt:new Date().toISOString()};s.condition=o[0];s.step=0;s.started=Date.now();log('session_start',{mode,order:o});go('learn')}
function head(){let p=Math.round(s.step/work.length*100),saying=s.step<3?`Lesson ${s.step+1} of 3`:`Question ${s.step-2} of 10`;return `<div class="ticker">LEARN • PRACTISE • EASY QUESTIONS • KEEP GOING</div><header class="study-head"><div class="study-head-inner"><div class="brand"><span class="brand-mark">${s.condition==='adapted'?'A':'S'}</span>${L[s.condition]}</div><div><div class="row" style="justify-content:space-between"><small>${saying}</small><small>${p}%</small></div><div class="progress-track"><div class="progress-fill" style="width:${p}%"></div></div></div><span class="pill">${s.step<3?'Lesson':'Easy test'}</span></div></header>`}
function learn(){let t=work[s.step];if(!t)return finish();let lesson=t[0]==='lesson';app.innerHTML=head()+`<main class="shell"><section class="stage"><span class="pill">${t[1]}</span><h1>${t[2]}</h1><div class="instruction">${t[3]}</div><div class="lesson-visual"><div style="font-size:${t[1]==='Emotions'?'8rem':'3rem'};font-weight:900">${t[4]}</div></div>${lesson?`<button class="btn" onclick="next()">Continue to ${s.step===2?'the test':'next lesson'}</button>`:`<div class="choice-grid">${t[5].map((x,i)=>`<button class="choice ${s.answer===i?'selected':''}" onclick="choose(${i})">${safe(x)}</button>`).join('')}</div>${s.feedback?`<div class="feedback ${s.feedback.ok?'':'error'}">${s.feedback.text}</div>`:''}<button class="btn" ${s.answer===null?'disabled':''} onclick="check()">${s.feedback?'Continue':'Check answer'}</button>`}<div class="assist-bar"><span class="muted">Researcher support</span><button class="btn secondary" onclick="help()">Log assistance</button></div></section></main>`}
function choose(i){s.answer=i;s.feedback=null;log('answer_selected',{answer:work[s.step][5][i]});draw()}function check(){let t=work[s.step];if(s.feedback)return next();let a=t[5][s.answer],ok=a===t[6];log(ok?'correct_answer':'incorrect_answer',{answer:a,correct:t[6]});s.feedback={ok,text:ok?'Correct. Well done!':'Answer recorded. Continue.'};draw()}function next(){let t=work[s.step];log('task_complete',{kind:t[0],subject:t[1],durationMs:Date.now()-s.started});s.step++;s.answer=null;s.feedback=null;s.started=Date.now();draw();scrollTo(0,0)}function help(){s.help++;log('assistance')}
function finish(){let e=s.events.filter(x=>x.condition===s.condition);s.results.push({condition:s.condition,questions:e.filter(x=>x.type==='task_complete'&&x.kind==='test').length,correct:e.filter(x=>x.type==='correct_answer').length,incorrect:e.filter(x=>x.type==='incorrect_answer').length,assistance:e.filter(x=>x.type==='assistance').length});save();go('survey')}
const qs=['It was easy to use.','I knew what would happen next.','I could focus.','The screen felt comfortable.','I would use it again.'];function survey(){app.innerHTML=head()+`<main class="shell"><section class="stage"><h1>How did this interface feel?</h1><form class="card" onsubmit="rate(event)">${qs.map((q,i)=>`<div class="likert"><span>${q}</span>${[1,2,3,4,5].map(n=>`<label>${n}<input type="radio" name="q${i}" value="${n}" required></label>`).join('')}</div>`).join('')}<button class="btn" style="margin-top:20px">Save</button></form></section></main>`}function rate(e){e.preventDefault();let f=new FormData(e.target),a=qs.map((_,i)=>+f.get('q'+i));s.results.at(-1).ratings=a;save();s.mode==='both'&&s.index===0?go('pause'):go('done')}
function pause(){app.innerHTML=`<main class="shell"><section class="hero"><div><h1>Take a short break.</h1><p class="lead">Continue only when the participant is ready.</p><button class="btn" onclick="second()">Start second interface</button></div><aside class="hero-card"><p class="big-number">10–15</p><h2>minutes suggested</h2></aside></section></main>`}function second(){s.index=1;s.condition=s.person.order[1];s.step=0;s.answer=null;s.started=Date.now();log('condition_start');go('learn')}
function done(){let n=s.results.reduce((a,r)=>({q:a.q+r.questions,c:a.c+r.correct,w:a.w+r.incorrect,h:a.h+r.assistance}),{q:0,c:0,w:0,h:0});app.innerHTML=`<main class="shell"><section class="stage"><h1>Session complete.</h1><div class="metrics">${[['Correct',n.c],['Incorrect',n.w],['Assistance',n.h]].map(x=>`<div class="metric"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('')}</div><button class="btn" style="margin-top:25px" onclick="download()">Export study data</button></section></main>`}function download(){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({participant:s.person,results:s.results,events:s.events},null,2)],{type:'application/json'}));a.download=`codex-study-${s.person.id}.json`;a.click()}
draw();
