/* EV-1.1 learning pathway — intentionally separate from the frozen study flow. */
(() => {
  const $ = id => document.getElementById(id);
  const completed = new Set(JSON.parse(localStorage.getItem("learnTogetherCompleted") || "[]"));
  const content = {
    maths:{title:"Number sense", kicker:"Maths · one step at a time", prompt:"Start with the counters. Then choose the answer.", kind:"maths", question:"What is 6 + 3?", options:["8","9","10"], answer:"9"},
    emotions:{title:"Face clues", kicker:"Emotions · look for clues", prompt:"Look at the picture. Notice the eyes and mouth.", kind:"emotions", question:"Which feeling matches this face?", options:["Happy","Sad","Surprised"], answer:"Happy"},
    english:{title:"Word detective", kicker:"English · use the clue", prompt:"Read the sentence. Pick the word that makes sense.", kind:"english", question:"The puppy ran very ___.", options:["fast","table","blue"], answer:"fast"}
  };
  function progress(){ const count=completed.size; $("learningProgressBar").style.width=(count/3*100)+"%"; $("learningProgressText").textContent=count+" "+(count===1?"activity":"activities")+" completed"; }
  function goHome(){ $("exploreHome").classList.remove("hidden");$("learningActivity").classList.add("hidden");$("toolkitPanel").classList.add("hidden");progress();window.scrollTo(0,0); }
  function start(key){
    const x=content[key], visual=x.kind==="maths"?'<div class="counters" aria-label="six counters plus three counters"><span>● ● ● ● ● ●</span><b>+</b><span>● ● ●</span></div>':x.kind==="emotions"?'<div class="emotion-face" aria-label="smiling face">🙂</div>':'<div class="sentence-clue">“The puppy ran very <strong>___</strong> to catch the ball.”</div>';
    $("exploreHome").classList.add("hidden");$("toolkitPanel").classList.add("hidden"); const el=$("learningActivity");el.classList.remove("hidden");
    el.innerHTML='<button class="back-link" type="button" data-explore-home>← Back to choices</button><div class="activity-card"><p class="eyebrow">'+x.kicker+'</p><h1>'+x.title+'</h1><p class="lead">'+x.prompt+'</p><div class="activity-visual">'+visual+'</div><p class="step-label">Practice question</p><h2>'+x.question+'</h2><div class="practice-options">'+x.options.map(o=>'<button type="button" data-answer="'+o+'">'+o+'</button>').join("")+'</div><p id="practiceFeedback" class="practice-feedback" role="status"></p><div class="activity-footer"><span>One question · no timer</span><button class="secondary-button" type="button" data-explore-home>Choose another lesson</button></div></div>';
    el.querySelectorAll("[data-answer]").forEach(b=>b.addEventListener("click",()=>{const good=b.dataset.answer===x.answer;el.querySelectorAll("[data-answer]").forEach(z=>z.disabled=true);b.classList.add(good?"correct":"try-again");const f=$("practiceFeedback");f.textContent=good?"Nice work — you found it. You can choose another activity when you are ready.":"That is okay. The answer is "+x.answer+". Try again in another activity when you feel ready.";if(good){completed.add(key);localStorage.setItem("learnTogetherCompleted",JSON.stringify([...completed]));progress();}})); window.scrollTo(0,0);
  }
  function toolkit(){ $("exploreHome").classList.add("hidden");$("learningActivity").classList.add("hidden");const el=$("toolkitPanel");el.classList.remove("hidden");el.innerHTML='<button class="back-link" type="button" data-explore-home>← Back to choices</button><div class="toolkit-card"><p class="eyebrow">Math toolkit</p><h1>Work it out your way.</h1><p class="lead">Use the buttons, the number line, or the counters. This is a learning support, not part of the research quiz.</p><div class="toolkit-grid"><section><h2>Calculator</h2><output id="calcDisplay" aria-live="polite">0</output><div class="calc-keys">'+["7","8","9","+","4","5","6","−","1","2","3","×","0","C","=","÷"].map(k=>'<button type="button" data-key="'+k+'">'+k+'</button>').join("")+'</div></section><section><h2>Number line</h2><input id="numberLine" type="range" min="0" max="20" value="0" aria-label="Choose a number from zero to twenty"><div class="number-readout"><strong id="numberReadout">0</strong><span>Move one step at a time.</span></div><div class="number-ticks">'+Array.from({length:21},(_,i)=>'<span>'+i+'</span>').join("")+'</div></section></div></div>';
    let expression=""; const display=$("calcDisplay");el.querySelectorAll("[data-key]").forEach(b=>b.onclick=()=>{let k=b.dataset.key;if(k==="C"){expression="";display.value="0";return}if(k==="="){try{expression=String(Function("return ("+expression.replaceAll("×","*").replaceAll("÷","/").replaceAll("−","-")+")")());display.value=expression}catch{display.value="Try again";expression=""}return}expression+=k;display.value=expression;});$("numberLine").oninput=e=>{$("numberReadout").textContent=e.target.value;};window.scrollTo(0,0);
  }
  document.addEventListener("click",e=>{const lesson=e.target.closest("[data-start-lesson]");if(lesson)start(lesson.dataset.startLesson);if(e.target.closest("[data-explore-home]"))goHome();if(e.target.closest("[data-toolkit]"))toolkit();if(e.target.closest("[data-open-research]")){ $("exploreView").classList.add("hidden"); document.getElementById("app").classList.remove("participant-mode");document.getElementById("app").classList.add("researcher-mode");document.querySelector(".explore-header").classList.add("hidden");document.querySelector(".researcher-header").classList.remove("hidden");document.getElementById("researcherView").classList.remove("hidden");window.scrollTo(0,0);}});
  progress();
})();